#!/bin/bash
set -e 
sudo docker stop $(sudo docker ps -q --filter ancestor=mikefrostov/main-app )
sudo docker rm $(sudo docker ps --all -q --filter ancestor=mikefrostov/main-app )
sudo docker build -t mikefrostov/main-app . 
sudo docker run -d -p 8084:8084 mikefrostov/main-app
